helm:
  parameters:
  - name: images.backend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-backend/api
    forcestring: true
  - name: images.backend.tag
    value: latest@sha256:da307d6d8d9922427a70e20009847b5814cb334d9db6abe72a4f9bcdb9f917f9
    forcestring: true
  - name: images.frontend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-frontend/frontend
    forcestring: true
  - name: images.frontend.tag
    value: latest@sha256:9b866a1580477efea04b4c434ec24934bf96fe0400fc1f44cc0e2ef7b983d62d
    forcestring: true
  - name: images.provisioner.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-provisioner/provisioner
    forcestring: true
  - name: images.provisioner.tag
    value: latest@sha256:0e9294c81749d799b55e7cb2ce7c6a8ebe5f61f29bc0f3bf1756041193245203
    forcestring: true
