helm:
  parameters:
  - name: images.backend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-backend/api
    forcestring: true
  - name: images.backend.tag
    value: latest@sha256:2055cc18e3fcb9946bf2bb8253fa3e716077acc454b27c6d84cd8f0558ae36ca
    forcestring: true
  - name: images.frontend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-frontend/frontend
    forcestring: true
  - name: images.frontend.tag
    value: latest@sha256:e014b40f8fb26b2f7d9e5885c6edb810cf3f864e517a6b03bc8c799c1c7749fe
    forcestring: true
  - name: images.provisioner.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-provisioner/provisioner
    forcestring: true
  - name: images.provisioner.tag
    value: latest@sha256:8730c69e0695e69c44efd5c686bb2664681fbffe7cd28564d07af421d6c45725
    forcestring: true
