helm:
  parameters:
  - name: images.backend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-backend/api
    forcestring: true
  - name: images.backend.tag
    value: latest@sha256:974e4220b5c52d3d0f66a7a2fd578e968e8e7e5db3b4b12a48d658961aa7d4d4
    forcestring: true
  - name: images.frontend.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-frontend/frontend
    forcestring: true
  - name: images.frontend.tag
    value: latest@sha256:9b866a1580477efea04b4c434ec24934bf96fe0400fc1f44cc0e2ef7b983d62d
    forcestring: true
  - name: images.provisioner.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/deer-flow-provisioner/provisioner
    forcestring: true
  - name: images.provisioner.tag
    value: latest@sha256:3f430c73acd3cf6ac76049ba787a6d64aeebc23a0bf5ba7bd056fb13360f4ee7
    forcestring: true
